# Generated by Django 5.1.4 on 2025-02-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('release_date', models.DateField()),
                ('actor', models.CharField(max_length=64)),
                ('actress', models.CharField(max_length=64)),
                ('language', models.CharField(max_length=64)),
                ('rating', models.FloatField()),
            ],
        ),
    ]
