# Generated by Django 5.1.4 on 2025-03-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('price', models.FloatField()),
                ('category', models.CharField(max_length=64)),
            ],
        ),
    ]
