# Generated by Django 5.1.4 on 2025-03-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('release_date', models.DateField()),
                ('actor', models.CharField(max_length=64)),
                ('actress', models.CharField(max_length=64)),
                ('language', models.CharField(max_length=64)),
                ('rating', models.FloatField()),
            ],
        ),
    ]
